Lab06-Dotnet/01_ButterfliesShop/ButterfliesShop/Models/Butterfly.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using System.ComponentModel.DataAnnotations;

namespace ButterfliesShop.Models
{
    public class Butterfly
    {
        public int Id { get; set; }

        [Display(Name = "Common Name")]
        [Required(ErrorMessage = "Please enter the butterfly name")]
        public string CommonName { get; set; }

        [Display(Name = "Butterfly Family")]
        public Family? ButterflyFamily { get; set; }

        [Display(Name = "Butterflies Quantity")]
        [Required(ErrorMessage = "Please select the butterfly quantity")]
        public int? Quantity { get; set; }

        [Display(Name = "Characteristics")]
        [Required(ErrorMessage = "Please type the characteristics")]
        [StringLength(50)]
        public string Characteristics { get; set; }

        [Display(Name = "Updated on")]
        [DataType(DataType.DateTime)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yy}", ApplyFormatInEditMode = true)]
        public DateTime CreatedDate { get; set; }

        [Display(Name = "Butterflies Picture")]
        [Required(ErrorMessage = "Please select the butterflies picture")]
        public IFormFile PhotoAvatar { get; set; }

        public string ImageName { get; set; }
        public byte[] PhotoFile { get; set; }
        public string ImageMimeType { get; set; }

    }
}

Lab06-Dotnet/01_ButterfliesShop/ButterfliesShop/Models/Family.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ButterfliesShop.Models
{
    public enum Family
    {
        Grassland,
        Nymphalidae,
        Danaine,
        Riodinidae
    }
}

Lab06-Dotnet/01_ButterfliesShop/ButterfliesShop/Models/IndexViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ButterfliesShop.Models
{
    public class IndexViewModel
    {
        public List<Butterfly> Butterflies { get; set; }
    }
}

Lab06-Dotnet/01_ButterfliesShop/ButterfliesShop/Controllers/ButterflyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ButterfliesShop.Models;
using ButterfliesShop.Services;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System.IO;

namespace ButterfliesShop.Controllers
{
    public class ButterflyController : Controller
    {
        private IDataService _data;
        private IHostingEnvironment _environment;
        private IButterfliesQuantityService _butterfliesQuantityService;

        public ButterflyController(IDataService data, IHostingEnvironment environment, IButterfliesQuantityService butterfliesQuantityService)
        {
            _data = data;
            _environment = environment;
            _butterfliesQuantityService = butterfliesQuantityService;
            InitializeButterfliesData();
        }

        private void InitializeButterfliesData()
        {
            if (_data.ButterfliesList == null)
            {
                List<Butterfly> butterflies = _data.ButterfliesInitializeData();
                foreach (var butterfly in butterflies)
                {
                    _butterfliesQuantityService.AddButterfliesQuantityData(butterfly);
                }
            }
        }

        public IActionResult GetImage(int id)
        {
            Butterfly requestedButterfly = _data.GetButterflyById(id);

            if (requestedButterfly != null)
            {
                string webRootpath = _environment.WebRootPath;
                string folderPath = @"\images\";
                string fullPath = webRootpath + folderPath + requestedButterfly.ImageName;

                if(System.IO.File.Exists(fullPath))
                {
                    FileStream fileOnDisk = new FileStream(fullPath, FileMode.Open);
                    byte[] fileBytes;

                    using (BinaryReader br = new BinaryReader(fileOnDisk))
                    {
                        fileBytes = br.ReadBytes((int)fileOnDisk.Length);
                    }

                    return File(fileBytes, requestedButterfly.ImageMimeType);
                }
                else
                {
                    if (requestedButterfly.PhotoFile.Length > 0)
                    {
                        return File(requestedButterfly.PhotoFile, requestedButterfly.ImageMimeType);
                    }
                }
            }
            

            return NotFound();
        }

        [HttpGet]
        public IActionResult Index()
        {
            IndexViewModel indexViewModel = new IndexViewModel();
            indexViewModel.Butterflies = _data.ButterfliesList;

            return View(indexViewModel);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Butterfly butterfly)
        {
            if (ModelState.IsValid)
            {
                Butterfly lastButterfly = _data.ButterfliesList.LastOrDefault();
                butterfly.CreatedDate = DateTime.Today;

                if (butterfly.PhotoAvatar != null && butterfly.PhotoAvatar.Length > 0)
                {
                    butterfly.ImageMimeType = butterfly.PhotoAvatar.ContentType;
                    butterfly.ImageName = Path.GetFileName(butterfly.PhotoAvatar.FileName);
                    butterfly.Id = lastButterfly.Id + 1;
                    _butterfliesQuantityService.AddButterfliesQuantityData(butterfly);

                    using (MemoryStream memoryStream = new MemoryStream())
                    {
                        butterfly.PhotoAvatar.CopyTo(memoryStream);
                        butterfly.PhotoFile = memoryStream.ToArray();
                    }

                    _data.AddButterfly(butterfly);

                    return RedirectToAction("Index");
                }

                return View(butterfly);
            }

            return View();
        }
    }
}

Lab06-Dotnet/01_ButterfliesShop/ButterfliesShop/Views/Butterfly/Create.cshtml
@model ButterfliesShop.Models.Butterfly
@using ButterfliesShop.Models

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
    <link type="text/css" rel="stylesheet" href="~/css/butterflies-shop-styles.css" />
</head>
<body>
    <div class="container">
        <h1 class=" main-title">Add Butterflies to the Shop</h1>
        <form method="post" enctype="multipart/form-data" asp-action="Create">
            <div asp-validation-summary="All">

            </div>

            <div class="form-field">
                <label asp-for="CommonName"></label>
                <input asp-for="CommonName" />
                <span asp-validation-for="CommonName"></span>
            </div>

            <div class="form-field">
                <label asp-for="ButterflyFamily"></label>
                <select asp-for="ButterflyFamily" asp-items="@Html.GetEnumSelectList<Family>()">
                    <option selected="selected">
                        Select
                    </option>
                </select>
                <span asp-validation-for="ButterflyFamily"></span>
            </div>

            <div class="form-field">
                <label asp-for="Characteristics"></label>
                <textarea asp-for="Characteristics"></textarea>
                <span asp-validation-for="Characteristics"></span>
            </div>

            <div class="form-field">
                <label asp-for="Quantity"></label>
                <input asp-for="Quantity" />
                <span asp-validation-for="Quantity"></span>
            </div>

            <div class="form-field">
                <label asp-for="PhotoAvatar"></label>
                <input asp-for="PhotoAvatar" />
                <span asp-validation-for="PhotoAvatar"></span>
            </div>


            <div class="form-field">
                <input type="submit" value="submit" />
            </div>
        </form>
    </div>
</body>
</html>

Lab06-Dotnet/01_ButterfliesShop/ButterfliesShop/Views/Butterfly/Index.cshtml
@model ButterfliesShop.Models.IndexViewModel

@{ Layout = null; }

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <link type="text/css" rel="stylesheet" href="~/css/butterflies-shop-styles.css" />
</head>
<body>
    <div class="container">
        <h1 class=" main-title">
            Butterflies Shop
        </h1>
        <p class="into">
            Welcome to our Web Store, Enjoy a Wide Variety of Butterflies
        </p>
        <p class="into">
            Our Butterflies in the Shop
        </p>
        <button type="button" onclick="location.href='@Url.Action("Create", "Butterfly")'">Add Butterflies</button>

        <div class="row">
            @foreach (var item in Model.Butterflies)
            {
<div class="col-10">

    <h1>@Html.DisplayFor(modelItem => item.CommonName)</h1>

    @if (item.ImageName != null)
    {
<div class="photo-display">
    <img class="photo-display-img" src="@Url.Action("GetImage", "Butterfly", new { Id = item.Id })" />
</div>          }

    <div class="display-info">
        <p class="display-label">
            @Html.DisplayNameFor(x => item.ButterflyFamily)
        </p><br />
        <p class="display-field">
            @Html.DisplayFor(x => item.ButterflyFamily)
        </p>
    </div>

    <div class="display-info">
        <p class="display-label">
            @Html.DisplayNameFor(x => item.Characteristics)
        </p>
        <p class="display-field">
            @Html.DisplayFor(x => item.Characteristics)
        </p>
    </div>
    <div class="display-info">
        <p class="display-label">
            @Html.DisplayNameFor(x => item.Quantity)
        </p>
        <p class="display-field">
            @Html.DisplayFor(x => item.Quantity)
        </p>
    </div>
    <div class="display-info">
        <p class="display-label">
            @Html.DisplayNameFor(x => item.CreatedDate)
        </p>
        <p class="display-field">
            @Html.DisplayFor(x => item.CreatedDate)
        </p>
    </div>
    <hr />
</div>      }
        </div>
    </div>
</body>
</html>

Lab06-Dotnet/01_ButterfliesShop/ButterfliesShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <script src="C:\Users\Admin\.nuget\packages\bootstrap\4.6.0\contentFiles\any\any\wwwroot\js\bootstrap.js"></script>
</head>
<body>
    <div>
        @RenderBody()
    </div>
</body>
</html>